version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  jdk:
    image: openjdk:latest
    container_name: jdk
    command: sleep infinity
    volumes:
      - jdk_volume:/usr/src/myapp
    working_dir: /usr/src/myapp

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"

volumes:
  postgres_data:
  jdk_volume:
